### ISSUE TITLE
Do you forgot the serializers file? 

### ISSUE THREAD

**Issue by bobyltr** [creimers/graphene-auth-examples#2]
ImportError while importing test module '/project/src/apps/account/test_mutations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/apps/account/test_mutations.py:1: in <module>
    from config.schema import schema
src/config/schema.py:3: in <module>
    from apps.account.mutations import (
src/apps/account/mutations.py:16: in <module>
    from .serializers import PasswordResetConfirmRetypeSerializer
E   ImportError: No module named 'apps.account.serializers'

**Comment by creimers** [comment]
@bobyltr Indeed, I forgot to check in a file. It should work now. Thanks!

**Comment by bobyltr** [comment]
It is working now ! 
Testing it...
Thanks a lot for writing this module.
