### ISSUE TITLE
How to receive email verification

### ISSUE THREAD

**Issue by Shuliyey** [creimers/graphene-auth-examples#6]
Hi

thanks a lot for making this greate example

just wondering what configuration i need to get activation email (send) working. I followed the instruction 

```bash
docker-compose build
docker-compose run django python ./src/manage.py migrate
docker-compose run -p 8000:8000 django python ./src/manage.py runserver 0.0.0.0:8000
```

I was able to register user successfully, however i don't see to received the email, i was expecting it to go to junk/spam

Cheers,
Zeyu

**Comment by creimers** [comment]
Hi Zeyu,

this project is configured to use the django console email backend. See how this is configured [here](https://github.com/creimers/graphene-auth-examples/blob/graphene-2/src/config/base_settings.py#L182).

The emails will be printed to the terminal where you are running the `docker-compose ... manage.py runserver`. 

If you want to receive the mails to a real world email address, you'll have to change the settings like so: https://docs.djangoproject.com/en/2.0/topics/email/#smtp-backend

I'm closing this issue. However, feel free of course to ask if something is not clear.
